In [1]:
import numpy as np

PI = np.array([0.5,0.5])
A = np.array([[0.2,0.8],
             [0.999,0.001]])
B = np.array([[0.05,0.35,0.2,0.2,0.2],
             [0.5,0.1,0.3,0.1,0.0]])
Observables = np.array([0,3,0,3,0])

In [2]:
def forward(PI,A,B,Observables):
    alpha = np.zeros(shape=(2,len(Observables)))
    i = 0
    j = 1
    
    alpha[i,0]=PI[i]*B[i][0]
    alpha[j,0]=PI[j]*B[j][0]

    for t in range(1,len(Observables)):
        alpha[i,t]=(alpha[i,t-1]*A[i][i]*B[i][i])+(alpha[j,t-1]*A[i][j]*B[i][i])
        alpha[j,t]=(alpha[i,t-1]*A[i][j]*B[j][i])+(alpha[j,t-1]*A[j][j]*B[j][i])

    return alpha

In [3]:
forward(PI,A,B,Observables)

array([[2.50000000e-02, 1.02500000e-02, 5.07500000e-04, 1.69277500e-04,
        9.89487625e-06],
       [2.50000000e-01, 1.01250000e-02, 4.10506250e-03, 2.05052531e-04,
        6.78135263e-05]])

In [4]:
def forward_normalized(PI,A,B,Observables):
    alpha = np.zeros(shape=(2,len(Observables)))
    c = np.zeros(len(Observables))
    i = 0
    j = 1
    
    print(c)
    alpha[i,0]=PI[i]*B[i][0]
    alpha[j,0]=PI[j]*B[j][0]
    c[0] = 1/(alpha[i,0]+alpha[j,0])
    alpha[i,0] *= c[0]
    alpha[j,0] *= c[0]

    for t in range(1,len(Observables)):
        alpha[i,t]=(alpha[i,t-1]*A[i][i]*B[i][i])+(alpha[j,t-1]*A[i][j]*B[i][i])
        alpha[j,t]=(alpha[i,t-1]*A[i][j]*B[j][i])+(alpha[j,t-1]*A[j][j]*B[j][i])
        c[t] = 1/(alpha[i,t]+alpha[j,t])
        alpha[i,t] *= c[t]
        alpha[j,t] *= c[t]

    return alpha,c

In [5]:
forward_normalized(PI,A,B,Observables)

[0. 0. 0. 0. 0.]


(array([[0.09090909, 0.50306748, 0.11002561, 0.45221459, 0.12733341],
        [0.90909091, 0.49693252, 0.88997439, 0.54778541, 0.87266659]]),
 array([ 3.63636364, 13.49693252,  4.41728432, 12.32218127,  4.8171114 ]))