In [14]:
import numpy as np

PI = np.array([0.5,0.5])
A = np.array([[0.2,0.8],
             [0.999,0.001]])
B = np.array([[0.05,0.35,0.2,0.2,0.2],
             [0.5,0.1,0.3,0.1,0.0]])
Observables = np.array([0,3,0,3,0])

In [17]:
def forward(PI,A,B,Observables):
    alpha = np.zeros(shape=(2,len(Observables)))
    i = 0
    j = 1
    
    alpha[i,0]=PI[i]*B[i][0]
    alpha[j,0]=PI[j]*B[j][0]

    for t in range(len(Observables)):
        if t == 0:
            continue
        else:
            alpha[i,t]=(alpha[i,t-1]*A[i][i]*B[i][i])+(alpha[j,t-1]*A[i][j]*B[i][i])
            alpha[j,t]=(alpha[i,t-1]*A[i][j]*B[j][i])+(alpha[j,t-1]*A[j][j]*B[j][i])
            
    return alpha

In [18]:
forward(PI,A,B,Observables)

[0. 0. 0. 0. 0.]


array([[2.50000000e-02, 1.02500000e-02, 5.07500000e-04, 1.69277500e-04,
        9.89487625e-06],
       [2.50000000e-01, 1.01250000e-02, 4.10506250e-03, 2.05052531e-04,
        6.78135263e-05]])

In [23]:
def forward_normalized(PI,A,B,Observables):
    alpha = np.zeros(shape=(2,len(Observables)))
    c = np.zeros(len(Observables))
    i = 0
    j = 1
    
    alpha[i,0]=PI[i]*B[i][0]
    alpha[j,0]=PI[j]*B[j][0]

    for t in range(len(Observables)):
        if t == 0:
            continue
        else:
            alpha[i,t]=(alpha[i,t-1]*A[i][i]*B[i][i])+(alpha[j,t-1]*A[i][j]*B[i][i])
            alpha[j,t]=(alpha[i,t-1]*A[i][j]*B[j][i])+(alpha[j,t-1]*A[j][j]*B[j][i])
            c = 1/(alpha[i,t]+alpha[j,t])
    return alpha,c

In [24]:
forward_normalized(PI,A,B,Observables)

(array([[2.50000000e-02, 1.02500000e-02, 5.07500000e-04, 1.69277500e-04,
         9.89487625e-06],
        [2.50000000e-01, 1.01250000e-02, 4.10506250e-03, 2.05052531e-04,
         6.78135263e-05]]), 12868.621251079347)